version: '3.8'

services:
  poky-builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./poky-build:/app/poky-build
    environment:
      - TERM=xterm-256color
    tty: true